[dependencies]
clap = '3.0.0-beta.2'
env_logger = '0.8.2'
handlebars = '3.5.2'
log = '0.4.14'
pulldown-cmark = '0.8.0'
rocket = '0.4.6'
serde_json = '1.0.62'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'simple_page'
version = '0.1.0'
