[dependencies]
clap = '3.0.0-beta.2'
env_logger = '0.7.1'
handlebars = '3.5.0'
log = '0.4.11'
pulldown-cmark = '0.8.0'
rocket = '0.4.5'
serde_json = '1.0.57'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'simple_page'
version = '0.1.0'
