[dependencies]
clap = '2.33.0'
env_logger = '0.7.1'
handlebars = '3.1.0-beta.1'
log = '0.4.8'
pulldown-cmark = '0.7.0'
rocket = '0.4.4'
serde_json = '1.0.51'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'simple_page'
version = '0.1.0'
