[global.limits]
forms = 32768
json = 1048576 # this is an extra used by the json contrib module
msgpack = 1048576 # this is an extra used by the msgpack contrib module


[development]
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
secret_key = "En+D9uPU2290TJ4keIDp4Y2wJuyUlVkx+lXymiyPvfs="
static_dir = "pagedata/static"
data_dir = "pagedata"
article_template = "pagedata/template/article.html"
dir_template = "pagedata/template/dir.html"


[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
secret_key = "En+D9uPU2290TJ4keIDp4Y2wJuyUlVkx+lXymiyPvfs="
static_dir = "pagedata/static"

[production]
address = "0.0.0.0"
port = 80
workers = 12
keep_alive = 5
log = "normal"
secret_key = "En+D9uPU2290TJ4keIDp4Y2wJuyUlVkx+lXymiyPvfs="
static_dir = "pagedata/static"