[global.limits]
forms = 32768
json = 1048576 # this is an extra used by the json contrib module
msgpack = 1048576 # this is an extra used by the msgpack contrib module

[development]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
# don't use this key! generate your own and keep it private!

[production]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
# don't use this key! generate your own and keep it private!
